version: '2.4'

services:
  www:
    environment:
      LAPIS_ENV: ${LAPIS_ENV}
    mem_limit: 50mb
    memswap_limit: 50mb
    image: karai17/lapis-centos:latest
    volumes:
      - ./www:/var/www
      - ./data:/var/data
    ports:
      - 10200:80
    restart: always
    command: bash -c "/usr/local/bin/docker-entrypoint.sh"
