version: '2.4'

services:

  www-singen-ca:
    mem_limit: 50mb
    memswap_limit: 50mb
    image: nginx:alpine
    volumes:
      - ./build:/usr/share/nginx/html
    restart: always

    # Development
    # ports:
    #   - 8080:80

networks:
  default:
    name: npm-net
    external: true
