version: '2.4'

services:

  www-singen-ca:
    environment:
      LAPIS_ENV: ${LAPIS_ENV}
    mem_limit: 50mb
    memswap_limit: 50mb
    image: karai17/lapis-centos:latest
    volumes:
      - ./www:/var/www
      - ./data:/var/data
    restart: always
    command: bash -c "/usr/local/bin/docker-entrypoint.sh"

networks:
  default:
    name: npm-net
    external: true
